name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: uname -a
    - name: Install dependencies
      run: |
        git clone https://github.com/FFmpeg/FFmpeg
        cd FFmpeg
        ./configure --arch=amd64 --disable-stripping --enable-openssl --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-shared --enable-nonfree
        make -j $(nproc)
        sudo make install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
